on:
  push:
    branches:
      - main
jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 0

    - name: Set up JDK 17.0.3+7
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17.0.3+7

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Read version.txt
      id: version
      uses: juliangruber/read-file-action@v1
      with:
          path: ./version.txt
      
    - name: export godot
      id: godot
      uses: manuel3108/github-godot-export@main
      with:
          godot_version: 3.4.4-stable
          use_mono: true
          base_dir: ./

    - name: create release
      uses: ncipollo/release-action@v1
      with:
          artifacts: ${{ steps.godot.outputs.artifacts }}
          generateReleaseNotes: true
          tag: v${{ steps.version.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}
