name: Export game

on:
  push:
    branches:
      - main
jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 0

    - name: Set up JDK 17.0.3+7
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17.0.3+7

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Read version.txt
      id: version
      uses: juliangruber/read-file-action@v1
      with:
          path: ./version.txt
    
    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@update-4
      with:
        # Defining all the required inputs
        # I used the mono version of Godot in this example
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_mono_export_templates.tpz
        relative_project_path: ./
        archive_output: true

    - name: create release
      # This release action has worked well for me. However, you can most likely use any release action of your choosing.
      # https://github.com/softprops/action-gh-release
      uses: softprops/action-gh-release@v0.1.14
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: true
        tag_name: v${{ steps.version.outputs.content }}
        files: ${{ steps.export.outputs.archive_directory }}/*
